name: deb-package

on:
  push:
    tags:
      - '*'
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    if: ${{ github.repository == 'rm-controls/rm_control' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic
      - name: Package deb
        uses: gdut-dynamic-x/ros-build-deb-action@v1
        with:
          ros_distro: noetic
          timestamp: true
      - name: Upload deb package to source
        if: ${{ github.repository == 'rm-controls/rm_control' }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SOURCE_SSH_HOST }}
          username: ${{ secrets.SOURCE_SSH_NAME }}
          key: ${{ secrets.SOURCE_SSH_KEYGEN }}
          port: ${{ secrets.SOURCE_SSH_PORT }}
          source: "*.deb"
          target: "/home/dynamicx/package_hub/wwwroot/ppa/incoming"
      - name: Deploy deb package to source
        if: ${{ github.repository == 'rm-controls/rm_control' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SOURCE_SSH_HOST }}
          username: ${{ secrets.SOURCE_SSH_NAME }}
          key: ${{ secrets.SOURCE_SSH_KEYGEN }}
          port: ${{ secrets.SOURCE_SSH_PORT }}
          script: |
                  cd /home/dynamicx/package_hub/wwwroot/ppa/
                  bash deploy.sh
