name: pre-release

on: [ workflow_dispatch ]

jobs:
  default:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: noetic }
          - { ROS_DISTRO: melodic }
    env:
      BUILDER: catkin_make_isolated
      PRERELEASE: true
      BASEDIR: ${{ github.workspace }}/.work
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ros-industrial/industrial_ci@master
        env: ${{ matrix.env }}
